// useful?
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const RENAME_CAT_TO_CINNAMON = "RENAME_CAT_TO_CINNAMON";
export const SET_NUMBER = "SET_NUMBER";
