require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  # so why?!?!?!?!
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  Pry.start
end
